### ISSUE TITLE
Repository not found. jmub0

### ISSUE THREAD

**Issue by MOA-YAD** [thejmthon/jmub#79]
https://github.com/thejmthon/jmub/blob/e3dc2ecb95d09c9574f498739e15b73b14b3bc52/README.md?plain=1#L65

# git clone https://github.com/thejmthon/jmub0
Cloning into 'jmub0'...
Username for 'https://github.com':
Password for 'https://github.com':
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/thejmthon/jmub0/'

**Comment by jmthonr** [comment]
oh done thanks
